FROM node:22-alpine

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@10.12.1 --activate

COPY package.json pnpm-lock.yaml .npmrc ./
RUN pnpm install --frozen-lockfile && \
    sha256sum pnpm-lock.yaml | cut -d " " -f 1 > node_modules/.pnpm-lock.sha256

COPY . .
COPY docker-entrypoint.dev /usr/local/bin/frontend-entrypoint
RUN sed -i "s/\r$//g" /usr/local/bin/frontend-entrypoint && \
    chmod +x /usr/local/bin/frontend-entrypoint

ENTRYPOINT ["frontend-entrypoint"]

EXPOSE 5173

CMD ["pnpm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
