# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  Exclude:
    - ".ruby-lsp/**/*"
    - "db/schema.rb"

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  Enabled: true

Layout/HashAlignment:
  Enabled: true

Layout/FirstArgumentIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent
