ARG RUBY_VERSION=4.0
FROM ruby:${RUBY_VERSION}-slim
ARG BUNDLER_VERSION=4.0

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      curl \
      default-libmysqlclient-dev \
      default-mysql-client \
      git \
      pkg-config && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV BUNDLE_PATH="/usr/local/bundle"

COPY Gemfile Gemfile.lock ./
RUN gem install bundler -v "~> ${BUNDLER_VERSION}.0" --no-document && bundle install

COPY . .
COPY bin/docker-entrypoint-dev /usr/local/bin/bookkeeping-entrypoint
RUN sed -i "s/\r$//g" /usr/local/bin/bookkeeping-entrypoint && \
    chmod +x /usr/local/bin/bookkeeping-entrypoint bin/* && \
    sed -i "s/\r$//g" bin/* && \
    sed -i 's/ruby\.exe$/ruby/' bin/*

ENTRYPOINT ["bookkeeping-entrypoint"]

EXPOSE 3000

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]
