@startuml additional_expenses

entity "additional_expenses" as additional_expenses {
    + id: bigint <<PK>>
    --
    # user_year_month_day_relation_id: bigint <<FK=user_year_month_day_relations.id, Not Null>>
    --
    additional_expense: bigint <<Not Null>>
    created_at: datetime <<Not Null>>
    updated_at: datetime <<Not Null>>
}

@enduml
