@startuml monthly_expense_details

entity "monthly_expense_details" as monthly_expense_details {
    + id: bigint <<PK>>
    --
    # user_year_month_id: bigint <<FK=user_year_months.id, Not Null, Unique>>
    --
    average_daily_expense: decimal <<Not Null>>
    total_monthly_expense: decimal <<Not Null>>
    predict_total_monthly_expense: decimal <<Not Null>>
    created_at: datetime <<Not Null>>
    updated_at: datetime <<Not Null>>
}

@enduml
