@startuml notes

entity "notes" as notes {
    + id: bigint <<PK>>
    --
    # additional_expense_id: bigint <<FK=additional_expenses.id, Not Null>>
    --
    note: string(255) <<Not Null>>
    created_at: datetime <<Not Null>>
    updated_at: datetime <<Not Null>>
}

@enduml
