@startuml users

entity "users" as users {
    + id: bigint <<PK>>
    --
    user_name: string(255) <<Not Null>>
    password: string(255) <<Not Null>>
    created_at: datetime <<Not Null>>
    updated_at: datetime <<Not Null>>
}

@enduml
