@startuml user_year_month_day_relations

entity "user_year_month_day_relations" as user_year_month_day_relations {
    + id: bigint <<PK>>
    --
    # user_id: bigint <<FK=users.id, Not Null>>
    # year_month_id: bigint <<FK=year_months.id, Not Null>>
    --
    day: bigint <<Not Null>>
    created_at: datetime <<Not Null>>
    updated_at: datetime <<Not Null>>
    --
    - (user_id, year_month_id) <<Composite Unique>>
}

@enduml
