@startuml year_months

entity "year_months" as year_months {
    + id: bigint <<PK>>
    --
    year: bigint <<Not Null>>
    month: bigint <<Not Null>>
    created_at: datetime <<Not Null>>
    updated_at: datetime <<Not Null>>
    --
    - (year, month) <<Composite Unique>>
}

@enduml
